POST http://localhost:8080/users/ HTTP/1.1
content-type: application/json

{
    "name": "Thiago Cifani",
    "username": "thiagocifani",
    "password": "12345678"
}

###

POST http://localhost:8080/tasks/ HTTP/1.1
content-type: application/json
Authorization: Basic thiagocifani:12345678

{
    "description": "Tarefa para gravar o curso de java",
    "title": "Gravacão de aula",
    "priority": "ALTA",
    "startAt": "2023-10-13T12:30:00" ,
    "endAt": "2023-10-12T17:30:00"
}
